name: CI

on: [ push, pull_request, workflow_dispatch ]

jobs:
    build:
        name: Build CuckooXtractor
        runs-on: ubuntu-latest
        
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              
            - name: Compile
              run: make
              
            - name: Upload
              uses: actions/upload-artifact@v3
              with:
                name: CuckooXtractor
                path: build/CuckooXtractor
